namespace:
  app: go-web-app
  gateway: gateway-system

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

gateway:
  name: go-web-app-gateway
  className: nginx
  listenerPort: 80

httproute:
  host: go-web-app.local


app:
  name: go-web-app
  replicas: 1
  image:
    repository: jpatel6625/go-web-app
    tag: "v1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  port: 8080



hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 50
