replicaCount: 1

image:
  repository: jpatel6625/go-web-app
  pullPolicy: IfNotPresent
  tag: "22409878307"

namespace:
  app: go-web-app
  gateway: gateway-system

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

gateway:
  name: go-web-app-gateway
  listenerPort: 80

httproute:
  host: go-web-app.local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"