apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace.gateway }}
spec:
  gatewayClassName: {{ .Release.Name }}-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listenerPort }}
      allowedRoutes:
        namespaces:
          from: All