# HTTPRoute resource for the application
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Values.namespace.gateway }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.namespace.gateway }}
  hostnames:
    - "go-web-app.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Release.Name }}-svc
          namespace: {{ .Values.namespace.app }}
          port: {{ .Values.service.port }}
