apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway
  namespace: {{ .Values.namespace.gateway }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.namespace.app }}
  to:
    - group: ""
      kind: Service
      namespace: {{ .Values.namespace.app }}
