apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.app }}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
status:
  loadBalancer: {}
