apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.app }}
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
status:
  loadBalancer: {}
